from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name = 'index')
    ,path('projects', views.projects, name = 'projects')
    ,path('project/<str:projectnumber>', views.project, name = 'project')
    ,path('projectcreate', views.projectcreate, name = 'projectcreate')
    ,path('project/<str:projectnumber>/docs', views.projectdocs, name = 'projectdocs')
    ,path('project/<str:projectnumber>/docs/<str:doctype>', views.projectdocs, name = 'projectdocs')
    ,path('project/<str:projectnumber>/docs/<str:doctype>/<str:action>/<int:pdid>', views.projectdocs_action, name = 'projectdocs_action')
    ,path('project/<str:projectnumber>/userdocs', views.projectuserdocs, name = 'projectuserdocs')
    ,path('project/<str:projectnumber>/remove/platform/<int:projectplatforminfoid>', views.projectplatforminfo_remove, name = 'projectplatforminfo_remove')
    ,path('project/<str:projectnumber>/remove/datallocation/<int:projectdatallocationid>', views.projectdatallocation_remove, name = 'projectdatallocation_remove')
    ,path('project/<str:projectnumber>/remove/dsdpcohort/<int:dsdpcohortid>', views.dsdpcohort_remove, name = 'dsdpcohort_remove')
    ,path('users', views.users, name = 'users')
    ,path('user/<int:usernumber>', views.user, name = 'user')
    ,path('usercreate', views.usercreate, name = 'usercreate')
    ,path('remove/userproject/<int:userprojectid>', views.userproject_remove, name = 'userproject_remove')
    ,path('remove/projectkristal/<int:projectkristalid>', views.projectkristal_remove, name = 'projectkristal_remove')
    ,path('grants', views.grants, name = 'grants')
    ,path('grant/<int:kristalnumber>', views.grant, name = 'grant')
    ,path('grantcreate', views.grantcreate, name = 'grantcreate')
    ,path('grants_no_routing', views.grants_no_routing, name = 'grants_no_routing')
    ,path('grants_update', views.grants_update, name = 'grants_update')
    ,path('dsas', views.dsas, name = 'dsas')
    ,path('dsa/<int:documentid>', views.dsa, name = 'dsa')
    ,path('dsacreate', views.dsacreate, name = 'dsacreate')
    ,path('remove/projectdsa/<int:dpid>', views.projectdsa_remove, name = 'projectdsa_remove')
    ,path('dataownercreate', views.dataownercreate, name = 'dataownercreate')
    ,path('transfers', views.transferrequests, name = 'transferrequests')
    ,path('transfer/<int:requestid>', views.transferrequest, name = 'transferrequest')
    ,path('transfercreate/<str:projectnumber>', views.transfercreate, name = 'transfercreate')
]