# Generated by Django 5.2.8 on 2026-03-31 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prism', '0008_tbltransferfile_tbltransferfileasset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbldsdpcohort',
            fields=[
                ('dsdpcohortid', models.AutoField(db_column='DSDPCohortID', primary_key=True, serialize=False)),
                ('cohort', models.CharField(blank=True, db_column='Cohort', max_length=25, null=True)),
                ('projectnumber', models.CharField(blank=True, db_column='ProjectNumber', max_length=25, null=True)),
            ],
            options={
                'db_table': 'tblDSDPCohort',
                'managed': False,
            },
        ),
    ]
