# Generated by Django 5.2.8 on 2026-04-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prism', '0009_tbldsdpcohort'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblPortfolioPlus',
            fields=[
                ('ppid', models.AutoField(db_column='ppid', primary_key=True, serialize=False)),
                ('grantstatus', models.CharField(blank=True, db_column='GrantStatus', max_length=12, null=True)),
                ('phasetype', models.CharField(blank=True, db_column='PhaseType', max_length=25, null=True)),
                ('phasestatus', models.CharField(blank=True, db_column='PhaseStatus', max_length=50, null=True)),
                ('grant', models.DecimalField(blank=True, db_column='Grant', decimal_places=0, max_digits=6, null=True)),
                ('longtitle', models.CharField(blank=True, db_column='LongTitle', max_length=255, null=True)),
                ('externalref', models.CharField(blank=True, db_column='ExternalRef', max_length=50, null=True)),
                ('pi', models.CharField(blank=True, db_column='PI', max_length=75, null=True)),
                ('location', models.CharField(blank=True, db_column='Location', max_length=50, null=True)),
                ('faculty', models.CharField(blank=True, db_column='Faculty', max_length=50, null=True)),
                ('researchstart', models.DateField(blank=True, db_column='ResearchStart', null=True)),
                ('researchend', models.DateField(blank=True, db_column='ResearchEnd', null=True)),
                ('outlinedate', models.DateField(blank=True, db_column='OutlineDate', null=True)),
                ('applicationdate', models.DateField(blank=True, db_column='ApplicationDate', null=True)),
                ('awarddate', models.DateField(blank=True, db_column='AwardDate', null=True)),
                ('leedsprice', models.DecimalField(blank=True, db_column='LeedsPrice', decimal_places=2, max_digits=11, null=True)),
                ('validfrom', models.DateTimeField(blank=True, db_column='ValidFrom', null=True)),
                ('validto', models.DateTimeField(blank=True, db_column='ValidTo', null=True)),
                ('createdby', models.CharField(blank=True, db_column='CreatedBy', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tblPortfolioPlus',
                'managed': False,
            },
        ),
    ]
